// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_ChartTemperature;
lv_obj_t * ui_Image1;
lv_obj_t * ui_labelTempValue;
lv_obj_t * ui_labelWindValue;
void ui_event_ButtonGate(lv_event_t * e);
lv_obj_t * ui_ButtonGate;
void ui_event_ButtonGarageGate(lv_event_t * e);
lv_obj_t * ui_ButtonGarageGate;
lv_obj_t * ui_LabelWindDirectionValue;
lv_obj_t * ui_LabelHumidityValue;
lv_obj_t * ui_LabelPressureValue;
lv_obj_t * ui_ImageHumidity;
lv_obj_t * ui_ImageTempOutside;
lv_obj_t * ui_ImageWind;
lv_obj_t * ui_ImageRain;
lv_obj_t * ui_ImageLight;
lv_obj_t * ui_ImageWindDirection;
lv_obj_t * ui_ImagePressure;
void ui_event_ButtonLightOutsideGarage(lv_event_t * e);
lv_obj_t * ui_ButtonLightOutsideGarage;
void ui_event_ButtonLightInsideGarage(lv_event_t * e);
lv_obj_t * ui_ButtonLightInsideGarage;
lv_obj_t * ui_LabelGarageOutsideLight;
lv_obj_t * ui_LabelGarageInsideLight;
// CUSTOM VARIABLES


// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
lv_obj_t * ui_Screen3;
lv_obj_t * ui_labelTempValueForecast;
lv_obj_t * ui_labelWindValueForecast;
lv_obj_t * ui_LabelWindDirectionValueForecast;
lv_obj_t * ui_LabelHumidityValueForecast;
lv_obj_t * ui_LabelPressureValueForecast;
lv_obj_t * ui_ImageHumidityForecast;
lv_obj_t * ui_ImageTempOutsideForecast;
lv_obj_t * ui_ImageWindForecast;
lv_obj_t * ui_ImageRainForecast;
lv_obj_t * ui_ImageLightForecast;
lv_obj_t * ui_ImageWindDirectionForecast;
lv_obj_t * ui_ImagePressureForecast;
void ui_event_ButtonRefresh(lv_event_t * e);
lv_obj_t * ui_ButtonRefresh;
lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
lv_obj_t * uic_ButtonRefresh;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_593525149[1] = {&ui_img_2048757971};
const lv_img_dsc_t * ui_imgset_867465873[1] = {&ui_img_1813840028};
const lv_img_dsc_t * ui_imgset_garage_[1] = {&ui_img_garage_5178_png};
const lv_img_dsc_t * ui_imgset_humidity_weather_icon_[1] = {&ui_img_humidity_weather_icon_129724_png};
const lv_img_dsc_t * ui_imgset_lightbulb_[1] = {&ui_img_lightbulb_114833_png};
const lv_img_dsc_t * ui_imgset_900268155[1] = {&ui_img_1694814665};
const lv_img_dsc_t * ui_imgset_462454381[1] = {&ui_img_1874206717};
const lv_img_dsc_t * ui_imgset_1121000734[1] = {&ui_img_111313662};
const lv_img_dsc_t * ui_imgset_1920294677[1] = {&ui_img_598496956};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ButtonGate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onGateClicked(e);
    }
}

void ui_event_ButtonGarageGate(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onGarageGateClicked(e);
    }
}

void ui_event_ButtonLightOutsideGarage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onGarageOutsideLightClick(e);
    }
}

void ui_event_ButtonLightInsideGarage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        onGarageInsideLightClick(e);
    }
}

void ui_event_ButtonRefresh(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refreshForecast(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen3_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
