// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ChartTemperature;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_labelTempValue;
extern lv_obj_t * ui_labelWindValue;
void ui_event_ButtonGate(lv_event_t * e);
extern lv_obj_t * ui_ButtonGate;
void ui_event_ButtonGarageGate(lv_event_t * e);
extern lv_obj_t * ui_ButtonGarageGate;
extern lv_obj_t * ui_LabelWindDirectionValue;
extern lv_obj_t * ui_LabelHumidityValue;
extern lv_obj_t * ui_LabelPressureValue;
extern lv_obj_t * ui_ImageHumidity;
extern lv_obj_t * ui_ImageTempOutside;
extern lv_obj_t * ui_ImageWind;
extern lv_obj_t * ui_ImageRain;
extern lv_obj_t * ui_ImageLight;
extern lv_obj_t * ui_ImageWindDirection;
extern lv_obj_t * ui_ImagePressure;
void ui_event_ButtonLightOutsideGarage(lv_event_t * e);
extern lv_obj_t * ui_ButtonLightOutsideGarage;
void ui_event_ButtonLightInsideGarage(lv_event_t * e);
extern lv_obj_t * ui_ButtonLightInsideGarage;
extern lv_obj_t * ui_LabelGarageOutsideLight;
extern lv_obj_t * ui_LabelGarageInsideLight;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_labelTempValueForecast;
extern lv_obj_t * ui_labelWindValueForecast;
extern lv_obj_t * ui_LabelWindDirectionValueForecast;
extern lv_obj_t * ui_LabelHumidityValueForecast;
extern lv_obj_t * ui_LabelPressureValueForecast;
extern lv_obj_t * ui_ImageHumidityForecast;
extern lv_obj_t * ui_ImageTempOutsideForecast;
extern lv_obj_t * ui_ImageWindForecast;
extern lv_obj_t * ui_ImageRainForecast;
extern lv_obj_t * ui_ImageLightForecast;
extern lv_obj_t * ui_ImageWindDirectionForecast;
extern lv_obj_t * ui_ImagePressureForecast;
void ui_event_ButtonRefresh(lv_event_t * e);
extern lv_obj_t * ui_ButtonRefresh;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ButtonRefresh;

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_supla_png);    // assets/supla.png
LV_IMG_DECLARE(ui_img_gate_png);    // assets/gate.png
LV_IMG_DECLARE(ui_img_garage_5178_png);    // assets/garage_5178.png
LV_IMG_DECLARE(ui_img_humidity_weather_icon_129724_png);    // assets/humidity_weather_icon_129724.png
LV_IMG_DECLARE(
    ui_img_1874206717);    // assets/thermometer-temperature-control-tool-weather-interface-symbol_icon-icons.com_54635.png
LV_IMG_DECLARE(ui_img_598496956);    // assets/wind-weather-lines-group-symbol_icon-icons.com_54629.png
LV_IMG_DECLARE(ui_img_1694814665);    // assets/rain-cloud_icon-icons.com_54268.png
LV_IMG_DECLARE(ui_img_1813840028);    // assets/clear-sun_icon-icons.com_54320.png
LV_IMG_DECLARE(ui_img_111313662);    // assets/wind-sock_icon-icons.com_54224.png
LV_IMG_DECLARE(ui_img_2048757971);    // assets/barometer-semicircular-outlined-tool-symbol_icon-icons.com_54699.png
LV_IMG_DECLARE(ui_img_lightbulb_114833_png);    // assets/lightbulb_114833.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
