// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void onGateClicked(lv_event_t * e);
void onGarageGateClicked(lv_event_t * e);
void onGarageOutsideLightClick(lv_event_t * e);
void onGarageInsideLightClick(lv_event_t * e);
void refreshForecast(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
