// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelTempValueForecast = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_labelTempValueForecast, 100);
    lv_obj_set_height(ui_labelTempValueForecast, 20);
    lv_obj_set_x(ui_labelTempValueForecast, -271);
    lv_obj_set_y(ui_labelTempValueForecast, -182);
    lv_obj_set_align(ui_labelTempValueForecast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTempValueForecast, "0.0");
    lv_obj_set_style_text_align(ui_labelTempValueForecast, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelWindValueForecast = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_labelWindValueForecast, 100);
    lv_obj_set_height(ui_labelWindValueForecast, 20);
    lv_obj_set_x(ui_labelWindValueForecast, -269);
    lv_obj_set_y(ui_labelWindValueForecast, -134);
    lv_obj_set_align(ui_labelWindValueForecast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelWindValueForecast, "0.0");
    lv_obj_set_style_text_align(ui_labelWindValueForecast, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindDirectionValueForecast = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelWindDirectionValueForecast, 200);
    lv_obj_set_height(ui_LabelWindDirectionValueForecast, 20);
    lv_obj_set_x(ui_LabelWindDirectionValueForecast, -223);
    lv_obj_set_y(ui_LabelWindDirectionValueForecast, -101);
    lv_obj_set_align(ui_LabelWindDirectionValueForecast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindDirectionValueForecast, "Poludniowo wschodni");
    lv_obj_set_style_text_align(ui_LabelWindDirectionValueForecast, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidityValueForecast = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelHumidityValueForecast, 100);
    lv_obj_set_height(ui_LabelHumidityValueForecast, 20);
    lv_obj_set_x(ui_LabelHumidityValueForecast, -269);
    lv_obj_set_y(ui_LabelHumidityValueForecast, -53);
    lv_obj_set_align(ui_LabelHumidityValueForecast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidityValueForecast, "0.0");
    lv_obj_set_style_text_align(ui_LabelHumidityValueForecast, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressureValueForecast = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_LabelPressureValueForecast, 100);
    lv_obj_set_height(ui_LabelPressureValueForecast, 20);
    lv_obj_set_x(ui_LabelPressureValueForecast, -269);
    lv_obj_set_y(ui_LabelPressureValueForecast, -9);
    lv_obj_set_align(ui_LabelPressureValueForecast, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPressureValueForecast, "0.0");

    ui_ImageHumidityForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageHumidityForecast, &ui_img_humidity_weather_icon_129724_png);
    lv_obj_set_width(ui_ImageHumidityForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHumidityForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHumidityForecast, -363);
    lv_obj_set_y(ui_ImageHumidityForecast, -55);
    lv_obj_set_align(ui_ImageHumidityForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHumidityForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHumidityForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageTempOutsideForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageTempOutsideForecast, &ui_img_1874206717);
    lv_obj_set_width(ui_ImageTempOutsideForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTempOutsideForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTempOutsideForecast, -368);
    lv_obj_set_y(ui_ImageTempOutsideForecast, -185);
    lv_obj_set_align(ui_ImageTempOutsideForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTempOutsideForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTempOutsideForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWindForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageWindForecast, &ui_img_598496956);
    lv_obj_set_width(ui_ImageWindForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWindForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWindForecast, -366);
    lv_obj_set_y(ui_ImageWindForecast, -139);
    lv_obj_set_align(ui_ImageWindForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWindForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWindForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRainForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageRainForecast, &ui_img_1694814665);
    lv_obj_set_width(ui_ImageRainForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRainForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageRainForecast, -366);
    lv_obj_set_y(ui_ImageRainForecast, 34);
    lv_obj_set_align(ui_ImageRainForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRainForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRainForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLightForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageLightForecast, &ui_img_1813840028);
    lv_obj_set_width(ui_ImageLightForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLightForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLightForecast, -366);
    lv_obj_set_y(ui_ImageLightForecast, 79);
    lv_obj_set_align(ui_ImageLightForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLightForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLightForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWindDirectionForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageWindDirectionForecast, &ui_img_111313662);
    lv_obj_set_width(ui_ImageWindDirectionForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWindDirectionForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWindDirectionForecast, -362);
    lv_obj_set_y(ui_ImageWindDirectionForecast, -98);
    lv_obj_set_align(ui_ImageWindDirectionForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWindDirectionForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWindDirectionForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePressureForecast = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImagePressureForecast, &ui_img_2048757971);
    lv_obj_set_width(ui_ImagePressureForecast, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePressureForecast, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePressureForecast, -368);
    lv_obj_set_y(ui_ImagePressureForecast, -14);
    lv_obj_set_align(ui_ImagePressureForecast, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePressureForecast, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePressureForecast, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonRefresh = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonRefresh, 100);
    lv_obj_set_height(ui_ButtonRefresh, 50);
    lv_obj_set_x(ui_ButtonRefresh, -317);
    lv_obj_set_y(ui_ButtonRefresh, 165);
    lv_obj_set_align(ui_ButtonRefresh, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRefresh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRefresh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_align(ui_ButtonRefresh, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -322);
    lv_obj_set_y(ui_Label2, 168);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Odswiez");

    lv_obj_add_event_cb(ui_ButtonRefresh, ui_event_ButtonRefresh, LV_EVENT_ALL, NULL);
    uic_ButtonRefresh = ui_ButtonRefresh;

}
