// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ChartTemperature = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_ChartTemperature, 470);
    lv_obj_set_height(ui_ChartTemperature, 292);
    lv_obj_set_x(ui_ChartTemperature, 124);
    lv_obj_set_y(ui_ChartTemperature, -80);
    lv_obj_set_align(ui_ChartTemperature, LV_ALIGN_CENTER);
    lv_chart_set_type(ui_ChartTemperature, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_ChartTemperature, 24);
    lv_chart_set_range(ui_ChartTemperature, LV_CHART_AXIS_PRIMARY_Y, -10, 30);
    lv_chart_set_range(ui_ChartTemperature, LV_CHART_AXIS_SECONDARY_Y, 980, 1035);
    lv_chart_set_axis_tick(ui_ChartTemperature, LV_CHART_AXIS_PRIMARY_X, 10, 5, 24, 2, true, 50);
    lv_chart_set_axis_tick(ui_ChartTemperature, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 5, 10, true, 50);
    lv_chart_set_axis_tick(ui_ChartTemperature, LV_CHART_AXIS_SECONDARY_Y, 10, 5, 5, 4, true, 25);
    lv_chart_series_t * ui_ChartTemperature_series_1 = lv_chart_add_series(ui_ChartTemperature, lv_color_hex(0x808080),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_ChartTemperature_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_ChartTemperature, ui_ChartTemperature_series_1, ui_ChartTemperature_series_1_array);
    lv_chart_series_t * ui_ChartTemperature_series_2 = lv_chart_add_series(ui_ChartTemperature, lv_color_hex(0x4900FF),
                                                                           LV_CHART_AXIS_SECONDARY_Y);
    static lv_coord_t ui_ChartTemperature_series_2_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 80, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_ChartTemperature, ui_ChartTemperature_series_2, ui_ChartTemperature_series_2_array);



    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_supla_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -321);
    lv_obj_set_y(ui_Image1, 184);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 100);

    ui_labelTempValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelTempValue, 100);
    lv_obj_set_height(ui_labelTempValue, 20);
    lv_obj_set_x(ui_labelTempValue, -271);
    lv_obj_set_y(ui_labelTempValue, -182);
    lv_obj_set_align(ui_labelTempValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelTempValue, "0.0");
    lv_obj_set_style_text_align(ui_labelTempValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_labelWindValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_labelWindValue, 100);
    lv_obj_set_height(ui_labelWindValue, 20);
    lv_obj_set_x(ui_labelWindValue, -269);
    lv_obj_set_y(ui_labelWindValue, -134);
    lv_obj_set_align(ui_labelWindValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelWindValue, "0.0");
    lv_obj_set_style_text_align(ui_labelWindValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGate = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonGate, 100);
    lv_obj_set_height(ui_ButtonGate, 100);
    lv_obj_set_x(ui_ButtonGate, 187);
    lv_obj_set_y(ui_ButtonGate, 179);
    lv_obj_set_align(ui_ButtonGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonGate, &ui_img_gate_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ButtonGate, lv_color_hex(0xFEFEFE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ButtonGate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ButtonGate, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_min_width(ui_ButtonGate, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_max_width(ui_ButtonGate, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonGarageGate = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonGarageGate, 100);
    lv_obj_set_height(ui_ButtonGarageGate, 100);
    lv_obj_set_x(ui_ButtonGarageGate, 319);
    lv_obj_set_y(ui_ButtonGarageGate, 180);
    lv_obj_set_align(ui_ButtonGarageGate, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonGarageGate, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonGarageGate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonGarageGate, &ui_img_garage_5178_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWindDirectionValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelWindDirectionValue, 200);
    lv_obj_set_height(ui_LabelWindDirectionValue, 20);
    lv_obj_set_x(ui_LabelWindDirectionValue, -223);
    lv_obj_set_y(ui_LabelWindDirectionValue, -101);
    lv_obj_set_align(ui_LabelWindDirectionValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWindDirectionValue, "Poludniowo wschodni");
    lv_obj_set_style_text_align(ui_LabelWindDirectionValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelHumidityValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelHumidityValue, 100);
    lv_obj_set_height(ui_LabelHumidityValue, 20);
    lv_obj_set_x(ui_LabelHumidityValue, -269);
    lv_obj_set_y(ui_LabelHumidityValue, -53);
    lv_obj_set_align(ui_LabelHumidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelHumidityValue, "0.0");
    lv_obj_set_style_text_align(ui_LabelHumidityValue, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelPressureValue = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelPressureValue, 100);
    lv_obj_set_height(ui_LabelPressureValue, 20);
    lv_obj_set_x(ui_LabelPressureValue, -269);
    lv_obj_set_y(ui_LabelPressureValue, -9);
    lv_obj_set_align(ui_LabelPressureValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelPressureValue, "0.0");

    ui_ImageHumidity = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageHumidity, &ui_img_humidity_weather_icon_129724_png);
    lv_obj_set_width(ui_ImageHumidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageHumidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageHumidity, -363);
    lv_obj_set_y(ui_ImageHumidity, -55);
    lv_obj_set_align(ui_ImageHumidity, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHumidity, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageHumidity, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageTempOutside = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageTempOutside, &ui_img_1874206717);
    lv_obj_set_width(ui_ImageTempOutside, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageTempOutside, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageTempOutside, -368);
    lv_obj_set_y(ui_ImageTempOutside, -185);
    lv_obj_set_align(ui_ImageTempOutside, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageTempOutside, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageTempOutside, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWind = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageWind, &ui_img_598496956);
    lv_obj_set_width(ui_ImageWind, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWind, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWind, -366);
    lv_obj_set_y(ui_ImageWind, -139);
    lv_obj_set_align(ui_ImageWind, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWind, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageRain = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageRain, &ui_img_1694814665);
    lv_obj_set_width(ui_ImageRain, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageRain, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageRain, -366);
    lv_obj_set_y(ui_ImageRain, 34);
    lv_obj_set_align(ui_ImageRain, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageRain, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageRain, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageLight = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageLight, &ui_img_1813840028);
    lv_obj_set_width(ui_ImageLight, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageLight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageLight, -366);
    lv_obj_set_y(ui_ImageLight, 79);
    lv_obj_set_align(ui_ImageLight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageLight, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWindDirection = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImageWindDirection, &ui_img_111313662);
    lv_obj_set_width(ui_ImageWindDirection, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImageWindDirection, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImageWindDirection, -362);
    lv_obj_set_y(ui_ImageWindDirection, -98);
    lv_obj_set_align(ui_ImageWindDirection, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageWindDirection, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWindDirection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImagePressure = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ImagePressure, &ui_img_2048757971);
    lv_obj_set_width(ui_ImagePressure, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImagePressure, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImagePressure, -368);
    lv_obj_set_y(ui_ImagePressure, -14);
    lv_obj_set_align(ui_ImagePressure, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImagePressure, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImagePressure, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ButtonLightOutsideGarage = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonLightOutsideGarage, 100);
    lv_obj_set_height(ui_ButtonLightOutsideGarage, 100);
    lv_obj_set_x(ui_ButtonLightOutsideGarage, -65);
    lv_obj_set_y(ui_ButtonLightOutsideGarage, 179);
    lv_obj_set_align(ui_ButtonLightOutsideGarage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLightOutsideGarage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLightOutsideGarage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonLightOutsideGarage, &ui_img_lightbulb_114833_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonLightInsideGarage = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonLightInsideGarage, 100);
    lv_obj_set_height(ui_ButtonLightInsideGarage, 100);
    lv_obj_set_x(ui_ButtonLightInsideGarage, 63);
    lv_obj_set_y(ui_ButtonLightInsideGarage, 179);
    lv_obj_set_align(ui_ButtonLightInsideGarage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonLightInsideGarage, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonLightInsideGarage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_ButtonLightInsideGarage, &ui_img_lightbulb_114833_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelGarageOutsideLight = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelGarageOutsideLight, 100);
    lv_obj_set_height(ui_LabelGarageOutsideLight, 20);
    lv_obj_set_x(ui_LabelGarageOutsideLight, -51);
    lv_obj_set_y(ui_LabelGarageOutsideLight, 108);
    lv_obj_set_align(ui_LabelGarageOutsideLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGarageOutsideLight, "Garaz zew.");

    ui_LabelGarageInsideLight = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelGarageInsideLight, 100);
    lv_obj_set_height(ui_LabelGarageInsideLight, 20);
    lv_obj_set_x(ui_LabelGarageInsideLight, 80);
    lv_obj_set_y(ui_LabelGarageInsideLight, 110);
    lv_obj_set_align(ui_LabelGarageInsideLight, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelGarageInsideLight, "Garaz wew.");

    lv_obj_add_event_cb(ui_ButtonGate, ui_event_ButtonGate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonGarageGate, ui_event_ButtonGarageGate, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLightOutsideGarage, ui_event_ButtonLightOutsideGarage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonLightInsideGarage, ui_event_ButtonLightInsideGarage, LV_EVENT_ALL, NULL);

}
